name: GitHub API Testing

# 触发条件：当代码被 push 或创建 pull request 时执行
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest  # 运行环境为 Ubuntu 最新版本

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 获取 GitHub 仓库的代码

      - name: Set up Python
